# For more info read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# To create additional roles in postgres see `$ createuser --help`.
# For details on connection pooling: https://guides.rubyonrails.org/configuring.html#database-pooling

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  database: <%= ENV.fetch("APP_DB_NAME", "app_#{Rails.env}") %>
  host: <%= ENV.fetch("APP_DB_HOST", "localhost") %>
  port: <%= ENV.fetch("APP_DB_PORT", 5432) %>
  username: <%= ENV.fetch("APP_DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("APP_DB_PASSWORD", nil) %>
  reconnect: true
  connect_timeout: 5 # seconds
  timeout: 5000 # milliseconds
  variables:
    statement_timeout: 15s # seconds
    lock_timeout: 10s # seconds
  # socket: /tmp/postgres.sock

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
