# user_engine

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in user_engine.gemspec.
gemspec path: "../.." # to user_engine.gemspec
