name: CI-engine-specs

on: workflow_call

jobs:
  setup-ruby:
    name: Setup Ruby
    runs-on: ubuntu-latest

    steps:
      - name: Checkout moduolar_monolith
        uses: actions/checkout@v2

      # TODO: read up on: https://github.com/ruby/setup-ruby/issues/105#issuecomment-726356409
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

  engine-specs:
    name: Run specs
    runs-on: ubuntu-latest
    needs: [ setup-ruby ]

    env:
      RAILS_ENV: test
      RAILS_MAX_THREAD: 5
      OSTYPE: linux # not set on GitHub's Ubuntu :-/
      APP_DB_NAME: engines_ci
      APP_DB_HOST: localhost
      APP_DB_PORT: 5432
      APP_DB_USERNAME: postgres
      APP_DB_PASSWORD: postgres

    services:
      postgres:
        # Docker Hub image
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_ci
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 4s
          --health-timeout 3s
          --health-retries 8

    steps:
      - name: Checkout moduolar_monolith
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1

      # TODO: caching
      - name: Bundle spec/dummy app
        run: |
          bundle install

      - name: Setup DB
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        run: |
          bundle install
          bundle exec rake db:create
          bundle exec rake db:schema:load

# --- till here it was only Ruby and Postgres DB Setup, now the tests are executed:

      - name: Run user_engine's test suite
        run: |
          bundle exec rake ci
