name: CI-push-main

on:
  push:
    branches: [ main ]

jobs:
  lint:
    uses: mediafinger/modular_monolith/.github/workflows/linter.yml@main

  test:
    uses: mediafinger/modular_monolith/.github/workflows/tests.yml@main

  # deploy_staging:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - lint
  #     - test
  #   steps:
  #     - name: Deploy to staging
